name: TerraformPlan

on:
  pull_request:
    branches:
      - main

env:
  TF_VERSION: 1.15.8
  AWS_DEFAULT_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check input
        if: inputs.lambda-layer-version == 'default'
        run: exit 1;

      - name: Check out repository code
        uses: actions/checkout@v3
    
      - name: Update terragrunt.hcl
        run: |
            sed -i.bak \
            "s|default = \".*\"|default = \"$LAYER_VERSION_ARN\"|" \
            infra/live/dev/terragrunt.hcl

            rm terragrunt.hcl.bak

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: |
            CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')
            echo "BRANCH_NAME=chore/update-layerー${CURRENT_DATETIME}" >> $GITHUB_ENV

      - name: Create PR
        run: |
            git checkout -b ${{ env.BRANCH_NAME }}

            git add terraform.tfvars
            git commit -m "Update Lambda Layer"

            git push origin ${{ env.BRANCH_NAME }}

            gh pr create \
            --title "Update Lambda Layer" \
            --body "Automated update of Lambda Layer version."
            --base dev
            --head ${{ env.BRANCH_NAME }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
